[package]
name = "stretcher"
version = "0.1.0"
authors = ["zukucker <alexander.froehling@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4"
